### ISSUE TITLE
咨询关于FAST-LIO与Move Base结合使用的研究论文及可能的研究发表

### ISSUE THREAD

**Issue by proxi666** [66Lau/NEXTE_Sentry_Nav#11]
您好，

我是一名学生，对您使用FAST-LIO和Move Base进行导航的项目非常感兴趣。我发现这一项目已在GitHub上开源，但似乎未找到详细讨论此整合技术的研究论文。请问您是否有相关的研究论文，或知道其他团队是否有相关发表？

另外，我在您的系统基础上集成了另一种开源算法，以进一步提升性能。请问在这种情况下，我可以就此改进的系统撰写研究论文吗？我希望能得到您的意见或建议，确保我的工作尊重原项目的贡献。

期待您的回复，并感谢您对这一领域的贡献！

**Comment by 66Lau** [comment]
FAST-LIO是港大团队的研究，Move Base是开源工具包，这两者合一起并没有什么自主的创新性，只是一些工程上的经验分享，所以没有论文。

如果你需要就该导航系统或者你的改进系统撰写论文，还请不要直接使用本项目的图片或者文字，你可以吸收之后用自己的话说出来，图片可以跑通代码后自己截图。

By the way, 我并不认为单纯的开源算法的堆叠足以支撑一篇研究论文，建议慎重考虑。

**Comment by proxi666** [comment]
您好，

首先感谢您的快速回复和宝贵建议。作为一名学生，我对这些技术的研究背景和创新性了解不多，您的解释对我非常有帮助。我理解单纯堆叠开源算法可能不足以撰写一篇有深度的研究论文，感谢您对此问题的指导。
