### ISSUE TITLE
有除了move_base框架外的其他处理局部代价地图的算法嘛？

### ISSUE THREAD

**Issue by dongjq23** [66Lau/NEXTE_Sentry_Nav#14]
您好，请问您探索过可以代替move_base中局部代价地图的算法嘛？我想对比分析一下，开源算法中是怎么进行地图更新与避障的，但是只知道move_base这一个优秀框架。

**Comment by 66Lau** [comment]
我尝试过CMU的自主探索导航系统，我认为不错。同样还有PUTN或者学术界比较新的一些端到端的算法都可以试试。
move_base中的dwa等局部规划算法在处理简单的规划问题我觉得是足够了的，主要还是工程上的优化能不能做好，还可以去看看ros2的navigation2

**Comment by dongjq23** [comment]
> 我尝试过CMU的自主探索导航系统，我认为不错。同样还有PUTN或者学术界比较新的一些端到端的算法都可以试试。 move_base中的dwa等局部规划算法在处理简单的规划问题我觉得是足够了的，主要还是工程上的优化能不能做好，还可以去看看ros2的navigation2

我大概知道啦!非常感谢!!
